### ISSUE TITLE
Do not automatically create .gitattributes.d

### ISSUE THREAD

**Issue by ghedo** [RichiH/vcsh#111]
Same as #49 but for `.gitattributes.d`. Something like `VCSH_GITATTRIBUTES=none` would be nice.

**Comment by nirvdrum** [comment]
While I can appreciate not creating the directory, I think there's value in setting the git config. I've just been burned again by git-crypt attributes not being picked up, despite my having created the `.gitattributes.d` directory. Is there any harm in always writing the git config value?
