### ISSUE TITLE
cannot pull repositories

### ISSUE THREAD

**Issue by prittjam** [RichiH/vcsh#137]
I am able to initialize, remote add, clone push, add to and commit to repositories, but when I pull, I get this cryptic message: 

e.g...
vcsh pull
emacs: fatal: /usr/libexec/git-core/git-pull cannot be used without a working tree.

matlab: fatal: /usr/libexec/git-core/git-pull cannot be used without a working tree.

mr: fatal: /usr/libexec/git-core/git-pull cannot be used without a working tree.

sh: fatal: /usr/libexec/git-core/git-pull cannot be used without a working tree.

vcsh doesn't seem to be know that $HOME is the working tree. I

any advice.

I use 
vcsh 1.20140508
git version 1.7.3.4

and followed the command sequence as stated (with changes to point to my github repositories) on the github vcsh page.

Kind Regards, James

**Comment by prittjam** [comment]
Thanks for the response. I have followed numerous tutorials, but I can't seem to even get a basic setup going. It's strange. Here is the command: 

vcsh clone https://github.com/prittjam/emacs.git

and the error

Initialized empty shared Git repository in /home/prittjam/.config/vcsh/repo.d/emacs.git/
remote: Counting objects: 1000, done.
remote: Compressing objects: 100% (824/824), done.
remote: Total 1000 (delta 134), reused 1000 (delta 134)
Receiving objects: 100% (1000/1000), 10.56 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (134/134), done.
From https://github.com/prittjam/emacs
 * branch            master     -> FETCH_HEAD
fatal: Not a valid object name origin/master
fatal: origin/master - not something we can merge

**Comment by prittjam** [comment]
I tried following this straightforward tutorial: http://www.martin-burger.net/blog/unix-shell/manage-dotfiles-quickly-and-effortlessly/

**Comment by nelg** [comment]
I've also encounted this problem, strangly only on one of my systems.
I'd like to help with providing details of the problem.

Would you like me to run vcsh -d clone ....
I wonder if it's related to the git version, which is: git version 1.8.1.5 on the affected system.

Oddly, after running vcsh clone .....xyz.git
then vcsh xyz pull   actually does pull the content OK.

**Comment by RichiH** [comment]
Yes, running with -d would help.

I have a suspicion of what may cause this, but setting it with -d would be
preferred.

Thanks!
Richard

Sent by mobile; excuse my brevity.

**Comment by nelg** [comment]
Sure, please see the linked pastebin of the debug output.
http://pastebin.com/yjBDVTdS

**Comment by RichiH** [comment]
Does origin/master exist?

If yes I will need to handle older versions of Git differently.

Richard

Sent by mobile; excuse my brevity.

**Comment by nelg** [comment]
Yes,.  I used a public repo so you could see.    As per command line below:
[nelg@zed tmp]$ git clone https://github.com/alourie/vcsh-zsh.git
Cloning into 'vcsh-zsh'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.
[nelg@zed tmp]$ cd vcsh-zsh/
[nelg@zed vcsh-zsh (master)]$ git config -l
user.email=nelg@linuxsolutions.co.nz
user.name=Glen Ogilvie
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/alourie/vcsh-zsh.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
[nelg@zed vcsh-zsh (master)]$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
[nelg@zed vcsh-zsh (master)]$ git checkout origin/master
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 5b0fad6... New updates with docker/boxen
[nelg@zed vcsh-zsh ((5b0fad6...))]$ git branch -a
* (no branch)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
[nelg@zed vcsh-zsh ((5b0fad6...))]$ git checkout master
Switched to branch 'master'
[nelg@zed vcsh-zsh (master)]$ git branch
* master
[nelg@zed vcsh-zsh (master)]$ git checkout origin/mastedf
error: pathspec 'origin/mastedf' did not match any file(s) known to git.
[nelg@zed vcsh-zsh (master)]$

**Comment by prittjam** [comment]
This problem does not occur with git 1.9.x My solution was to upgrade git, but the problem still exists with older versions of git.

**Comment by RichiH** [comment]
I can't find the commit which caused the issue via plain code review.

Do you still happen to have a machine with Git 1.8 and would be willing to `git bisect`?

**Comment by liquidstate** [comment]
Hi, I've got this problem too... and I'm happy to help with testing.

```
$ cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

$ git --version
git version 1.8.3.1

$ vcsh clone git@github.com:liquidstate/vcsh-root.git mr
Initialized empty shared Git repository in /root/.config/vcsh/repo.d/mr.git/
Switched to a new branch 'master'
remote: Counting objects: 266, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 266 (delta 3), reused 0 (delta 0), pack-reused 252
Receiving objects: 100% (266/266), 81.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (55/55), done.
From github.com:liquidstate/vcsh-root
 * branch            master     -> FETCH_HEAD
fatal: Not a valid object name origin/master
fatal: origin/master - not something we can merge

$ git clone git@github.com:liquidstate/vcsh-root.git
Cloning into 'vcsh-root'...
remote: Counting objects: 307, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 307 (delta 3), reused 0 (delta 0), pack-reused 293
Receiving objects: 100% (307/307), 92.84 KiB | 0 bytes/s, done.
Resolving deltas: 100% (76/76), done.

$ git config -l
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@github.com:liquidstate/vcsh-root.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master

$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/bootstrap
  remotes/origin/master
```

**Comment by liquidstate** [comment]
And, it seems to work okay with git 1.9.4:

```
$ yum -y scl-utils
$ yum -y install git19

$ git --version
git version 1.9.4

vcsh clone git@github.com:liquidstate/vcsh-root.git mr
Initialized empty shared Git repository in /root/.config/vcsh/repo.d/mr.git/
Switched to a new branch 'master'
remote: Counting objects: 266, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 266 (delta 3), reused 0 (delta 0), pack-reused 252
Receiving objects: 100% (266/266), 81.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (55/55), done.
From github.com:liquidstate/vcsh-root
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
```

**Comment by bremner** [comment]
Bisecting with git 1.8.3.1 yields 589f2baa284376cbbe5e98d5f5ff145a9441dffc as the first bad commit.

At some point the error message changed to 

vcsh: fatal: 61173a8aa6aa950543d1282d54097984441f427f	refs/heads/master
/home1/faculty/bremner/bin/vcsh: line 27: [: missing `]'

**Comment by leycec** [comment]
**I can confirm this as well.** In my case, on the positively geriatric `git 1.7.12.4`. (_Don't ask; don't tell._) :older_man: 

@bremner Thanks for bisecting the offending commit! Your commitment to truth and knowledge is an example for us all.

**Comment by alerque** [comment]
I think this is a non issue:

* Git 1.7 was positively geriatric 6 years ago. I don't know if we've declared a minimum Git version at this point, but I think it's reasonable to expect 2+ now. Even the oldest Ubuntu LTS release in the wild (Xenial 16.04) has 2.7 . and the oldest live Debian LTS (stretch) is at 2.11.
* Since this issue was written the hard coded `master` branch has gained an option  to use a different branch name, alleviating one possible reason this error condition could have been triggered.
* The clone option has gained a new check that verifies the remote is accessible *before* doing anything locally, hence certain connection and negotiation issues should be caught earlier and not trip us up here.

If I'm missing anything and this is still an issue that needs fixing somebody please chime in and I'll re-open.
