### ISSUE TITLE
Error on initial clone: vcsh: error: 'file' exists.

### ISSUE THREAD

**Issue by Hubbitus** [RichiH/vcsh#150]
```
$ mkdir ssh:private
[pasha@hubbitus .ssh]$ cd ssh:private/
[pasha@hubbitus ssh:private]$ vcsh clone backup@git.hubbitus.info:git/ssh:private ssh:private
Initialized empty shared Git repository in /home/pasha/.config/vcsh/repo.d/ssh:private.git/
Switched to a new branch 'master'
remote: Counting objects: 23, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 23 (delta 7), reused 0 (delta 0)
Unpacking objects: 100% (23/23), done.
From git.hubbitus.info:git/ssh:private
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
vcsh: error: 'README' exists.
vcsh: error: 'TolikKur_ant_rsa' exists.
vcsh: error: 'TolikKur_ant_rsa.pub' exists.
vcsh: error: 'authorized_keys' exists.
vcsh: error: 'aws-free-test.pem' exists.
vcsh: error: 'config' exists.
vcsh: error: 'fedora_rsa' exists.
vcsh: error: 'fedora_rsa.pub' exists.
vcsh: error: 'id_rsa' exists.
vcsh: error: 'id_rsa.desktop' exists.
vcsh: error: 'id_rsa.pub' exists.
vcsh: error: 'id_rsa.pub.desktop' exists.
vcsh: error: 'known_hosts' exists.
vcsh: fatal: will stop after fetching and not try to merge!
  Once this situation has been resolved, run 'vcsh ssh:private pull' to finish cloning.
```

**Comment by vdemeester** [comment]
I'm not sure of what you'r trying to do here. More context would have been appreciated ;-).

But from what I see, you are *vcsh cloning* a repository that has files already present (in another vcsh repository or on the filesystem with no repository). ``vcsh`` won't try to overrite them. I'm not sur why you are doing the ``mkdir`` as vcsh will always clone in ``$HOME/.config/vcsh/repo.d`` (or ``$XDG_CONFIG_DIR/vcsh/repo.d``) and will use ``$HOME`` as the working directory. If you want to clone ``backup@git.hubbitus.info:git/ssh:private`` in a separate folder, you might just want to do a simple ``git clone``

```bash
$ git clone backup@git.hubbitus.info:git/ssh:private ssh:private
```

Let me know if I kinda go it right or if you're trying something else I didn't get :).

**Comment by RichiH** [comment]
As Vincent says, you seem to be trying to clone over existing stuff which
vcsh prevents.

As an aside, having a README may be a bad idea as if any other repo also
has one, they will fight over control of that file, leading to a lot of
spurious commits.

**Comment by Hubbitus** [comment]
Thank you very much for comments. I indeed misunderstood concept initially. Is there somewhere described how I use other than $HOME directory (current)?

**Comment by RichiH** [comment]
There is an agnostic branch, but it's not merged yet as I am still not
happy with the overall design.

**Comment by Hubbitus** [comment]
Do you speak about https://github.com/RichiH/vcsh/tree/feature/agnostic?

**Comment by RichiH** [comment]
Yes.

Richard

Sent by mobile; excuse my brevity.

**Comment by Hubbitus** [comment]
Thank you. I think It may be closed now.

**Comment by RichiH** [comment]
As a follow-up, you could use `readme.d/ssh:private`, `readme.d/zshrc` etc etc.

That way you can maintain your READMEs yet have clean namespaces.

**Comment by Hubbitus** [comment]
My initial intension was to maintain .ssh/config, .ssh/id_rsa.pub in ssh:public, and .ssh/id_rsa in another ssh:private repos and clone hem into .ssh/ . Now I just in each create .ssh/ subfolder and commit it to manage from ~/, but it is not looks so good.
