### ISSUE TITLE
Ability to install vcsh without root privileges?

### ISSUE THREAD

**Issue by absorber** [RichiH/vcsh#151]
On some systems I don't always have ability to perform privileged tasks, but would like to have the ability to install vcsh.
Also, if I am understanding the [makefile](https://github.com/RichiH/vcsh/blob/master/Makefile) correctly, the install mostly puts (the doc) files into `/usr/`.

Would it be possible to somehow add vcsh (and necessary files) to local user's path only?

**Comment by ncanceill** [comment]
A proper vcsh install needs a proper folder architecture, namely:
* `usr/bin`
* `usr/share/doc`
* `usr/share/man/man1`

Usually those folders are in `/`, but if you want to chroot it somewhere else, for instance `/home/jeanbaptiste/my_chroot` that would be:
```bash
make install DESTDIR=/home/jeanbaptiste/my_chroot
```

***

If you do not care about a proper install, and just want the program somewhere, say `/home/jeanedouard/my_programs`, then you can simply do:
```bash
install -m 0755 /path/to/vcsh /home/jeanedouard/my_programs
```

***

In both cases you will need to add the relevant folders to the user's `$PATH` yourself.

**Comment by RichiH** [comment]
Also, you can simply copy over the shell script in, e.g. `~/bin/` if you don't need the manpage, completions, etc.

**Comment by RichiH** [comment]
Please also see bcca0cb
