### ISSUE TITLE
proper handing of repos with 2+ words in name

### ISSUE THREAD

**Issue by ZuBB** [RichiH/vcsh#159]
```
vv@e5520 ~ $ vcsh init 'multiword test'
/usr/bin/vcsh: 435: [: multiword: unexpected operator
Initialized empty Git repository in /home/vv/.config/vcsh/repo.d/multiword test.git/
vv@e5520 ~ $ 
```
I think vcsh should do full stop (and print message) on attempt to use 2+ words as repo name

ps I am running (x)ubuntu 14.04.2

**Comment by vdemeester** [comment]
Not sure if it's vcsh related or common bash stuff as the following is working.

```bash
$ vcsh init multiword\ test                                                        
Initialized empty shared Git repository in /home/vincent/.config/vcsh/repo.d/multiword test.git/
```

**Comment by ZuBB** [comment]
repo also was created in my case. but before that some error occured..

**Comment by RichiH** [comment]
What version are you using? Both work for me even though I do _not_ officially support this. `vcsh` should be, and stay, resilient enough to handle it, though.

`test@titanium:~$ vcsh init multiword\ test
Initialized empty shared Git repository in /home/test/.config/vcsh/repo.d/multiword test.git/
test@titanium:~$ vcsh init 'multiword test2'
Initialized empty shared Git repository in /home/test/.config/vcsh/repo.d/multiword test2.git/
test@titanium:~$`

**Comment by ZuBB** [comment]
```
vv@vv-Latitude-E5520 ~ $ vcsh version
vcsh 1.20131229
git version 1.9.3
vv@vv-Latitude-E5520 ~ $ 
```

**Comment by RichiH** [comment]
That version is ancient; can you try with a current one from Git HEAD?

**Comment by ZuBB** [comment]
wi try to look on this on weekend

**Comment by ZuBB** [comment]
yes, with latest sources (feature/pull_--quiet barch) all is OK
