### ISSUE TITLE
"vcsh which" parameter check broken

### ISSUE THREAD

**Issue by tribut** [RichiH/vcsh#168]
As discussed on IRC, since https://github.com/RichiH/vcsh/commit/d946b07817ffe6e156c159e7fc6270322413e530 `vcsh which` no longer accepts a substring as documented but expects the full path to a file that exists in the work tree.
The correct way to determine the exit code would probably be to remember if `grep` ever returned 0 (matched anything).

**Comment by RichiH** [comment]
`sed` is [part of POSIX](http://pubs.opengroup.org/onlinepubs/009695399/utilities/sed.html) so the new external dependency is fine.

I really dislike that we would need another tempfile. I like the substring part, though.

All in all, wouldn't it be more versatile to see if there's any output from the loop and error out if that output is empty?

**Comment by RichiH** [comment]
@tribut : I just cherry-picked your b3d7fb34868229489a1216f810a004089665bcbf and I think I will merge 9cf8f5c46b230abd912657aeac276e4a2ce38ce0 into master unless you object.

**Comment by tribut** [comment]
Seems fine.

**Comment by RichiH** [comment]
Thanks :)
