### ISSUE TITLE
add bash_completion functionality

### ISSUE THREAD

**Issue by andreas-h** [RichiH/vcsh#170]
It would be great if vcsh would include a bash_completion script, which the user could plug into `/etc/bash_completion.d`.  For example, I could then type

```
vcsh e <TAB>
```

and have 

```
vcsh emacs
```

in my terminal.  This would save quite some typing.

**Comment by alerque** [comment]
There are completion routines for `vcsh` already. It sounds like you may not have them installed properly. What distro are you using and how did you go about installing `vcsh`?

**Comment by andreas-h** [comment]
I'm on Debian sid.  I just checked the Debian package and could see that a script `_vcsh` is installed to `/usr/share/zsh/vendor-completions/`.  Should the `_vcsh` in this repo work with Bash and zsh?  If so, I'll file a bug against the Debian package ...

**Comment by alerque** [comment]
@andreas-h I don't know about that. It's been a while since I've used bash. That may need to be converted to another format before bash can make sense of it. Might have to wait for somebody in the know on that one.

**Comment by RichiH** [comment]
AFAIK, you need to write Bash completions in Bash's language. You could try tossing this onto the Bash mailing lists or similar. I will gladly include any such completions in vcsh, but I lack the time, and motivation, to do this myself.

**Comment by bertenvdb** [comment]
Having read [this](https://www.debian-administration.org/article/316/An_introduction_to_bash_completion_part_1) I came up with https://github.com/bertenvdb/vcsh_bash_completion
It's not perfect, but for now that's the best I can do, not really knowing much about bash or coding in general. I also don't even use vcsh that much anymore, my configs are pretty stable ATM :-)

**Comment by rhopfer** [comment]
I add one to [my fork](https://github.com/rhopfer/vcsh). I will test it a little bit and make a PR if it works properly.
