### ISSUE TITLE
vcsh list -v does nothing

### ISSUE THREAD

**Issue by QuinnyPig** [RichiH/vcsh#173]
Maybe I'm thinking about this the wrong way, but to my mind vcsh list -v should be functionally close to:

```
for i in $(vcsh list); do vcsh run $i git remote -v; done
```

The goal being to grab a list of what the vcsh remote source(s) is set to on one node and quickly add it to another node.

**Comment by rhopfer** [comment]
I think `vcsh list -v` is not a valid command (contrary to `vcsh -v list`).

**Comment by RichiH** [comment]
`vcsh list -v` -> "this option is for `git list`"
`vcsh -v list` -> "this option is for `vcsh`"
