### ISSUE TITLE
Expose verbose and debug flags to vcsh hooks?

### ISSUE THREAD

**Issue by nfarrar** [RichiH/vcsh#175]
Would it be possible to expose the debug and verbose flags to vcsh hooks?

**Comment by vdemeester** [comment]
@nfarrar I think this could be done and would be cool :wink:

**Comment by nfarrar** [comment]
Write now I've added a bunch of verbose information to my hooks (for testing while writing them) ... it'd be nice to leave those in now that they're working, and have it hidden except when needed (i.e. something breaks).

**Comment by vdemeester** [comment]
@nfarrar yeah that's an idea :+1:. I tend to use that on my usual git repository (with a little message to know it's working though :stuck_out_tongue_closed_eyes:).

**Comment by nfarrar** [comment]
Just checking back in on this. :) Rewrote my hooks with some configurable verbosity. Would be awesome to expose these options to them:

- https://github.com/nfarrar/dotfiles/blob/master/.config/vcsh/hooks-available/backup-conflicts
- https://github.com/nfarrar/dotfiles/blob/master/.config/vcsh/hooks-available/configure-sparsecheckout

**Comment by ao2** [comment]
Right now hooks are child processes, in principle they could be written in any programming language.

If this will stays that way the best that can be done is to export the env variables `VCSH_VERBOSE` and `VCSH_DEBUG` and have hooks use them as they wish.

**Comment by alerque** [comment]
cf. #68 for another way of making hooks powerful, and cf. #276 for another variable export related feature request. One feature can probably cover both this and #276 by doing by default for hooks whatever the new `vcsh dump_vars` does.

**Comment by RichiH** [comment]
The one risk I can see is that `-v` and `-d` might do different things for hooks, in particular after a decade of organic growth. Sorry for not engaging with this a _lot_ earlier.

@ao2 @nfarrar @vdemeester What about https://github.com/RichiH/vcsh/pull/291 ? Does that help with your use case?

**Comment by RichiH** [comment]
Trivial test hook script to verify:

````
echo hookscript $0
echo "debug: $VCSH_DEBUG"
echo "verbose: $VCSH_VERBOSE"
````

**Comment by alerque** [comment]
Yes. I think exposing these via the environment variables rather than passing them any CLI flags is the right thing to do. This will also translate nicely to #276.

**Comment by RichiH** [comment]
As an update, https://github.com/RichiH/vcsh/pull/292 is an even more aggressive interpretation of this feature request. This should cover ALL that things.

**Comment by ao2** [comment]
Thanks folks, this looks nice!
