### ISSUE TITLE
Skip ignored files in the output of list-untracked

### ISSUE THREAD

**Issue by hvhaugwitz** [RichiH/vcsh#181]
Please add '--exclude-standard' to the 'git ls-files' call of the list_untracked_helper function by default to skip ignored files in the output and add '-a' option to list all files.

**Comment by tjaartvdwalt** [comment]
I second this request.

It would allow me to easily see which files have not been ignored or added to a repository. These are the files I need to give attention to.

**Comment by RichiH** [comment]
Please see that branch and get back to me.

**Comment by hvhaugwitz** [comment]
Looks good, thanks!
