### ISSUE TITLE
how to show vcsh repo name in bash prompt

### ISSUE THREAD

**Issue by QiangF** [RichiH/vcsh#182]
Hi Everyone,
I have several terminal tabs open. I often add file of repo A to repo B, because I forget which terminal tab is for which repo. 
Thank you!

**Comment by nfarrar** [comment]
The way it's typically done with git is to check for a .git directory, then parse the name. You *can't really* do this with VCSH - however, you can use the approach that's usually taken with python virtual environments.

When you use 'vcsh enter' to 'enter' a vcsh repo - vcsh sets the environment variable `VCSH_REPO_NAME=<repo>`. So, in your bash prompt, check if that environment variable is set, and if it is, display the name. :)

**Comment by QiangF** [comment]
That's a neat solution. Thank you!
