### ISSUE TITLE
Exclude ~/.config/vcsh dir from the repo?

### ISSUE THREAD

**Issue by dimio** [RichiH/vcsh#184]
Hello.
I add all files from `$HOME` to my repo using `git add :/`.
Directory `~/.config/vcsh/` also included into the repo. I should exclude `~/.config/vcsh/` or `~/.config/vcsh/**/objects/` (or another dirs in `~/.config/vcsh/`) using the `.gitignore`?

**Comment by RichiH** [comment]
Correct, you should exclude `~/.config/vcsh/` if you blanket add _all_ your home directory.

If you just want to toss _everything_ into one big repo, you could even use plain git and ignore `vcsh`

The advantage of using `vcsh` is that you are able to put more than one repo in `$HOME` - and then it does not make sense to just add everything, anyway.
