### ISSUE TITLE
Add ability to choose Readme and Licence file locations

### ISSUE THREAD

**Issue by ywecur** [RichiH/vcsh#192]
Currently addling a readme or license file to a repo just places it into the home folder. 

I understand that you can solve this with external hacks, but IMO this is a common enough issue that a built in solution should be provided.

**Comment by RichiH** [comment]
I have been pondering this off and on again, but I can't come up with anything native, yet nice; and something that does not violate the principle of least surprise.

Possible approaches:

* Different branches
* Ignore README and LICENSE while cloning and pulling
* Abusing smudge/clean filters

But I can't say I am happy with any of these...

**Comment by ao2** [comment]
Related to #120: having sparse checkout and ignoring colliding files seems to be the more lightweight solution.

**Comment by alerque** [comment]
I think this issue is effectively a duplicate of #120. Whatever solution we even find (if only) will pretty much have to solve both use cases.
