### ISSUE TITLE
vcsh and mr integration for status command

### ISSUE THREAD

**Issue by brabalan** [RichiH/vcsh#194]
It seems that `mr status` runs a `vcsh foo status` command for repository `foo`, which includes all the untracked files. I’ve changed it in the mr configuration for that repository, but could is be possible to have the default be `vcsh status foo` instead?

**Comment by RichiH** [comment]
Good idea. This is a Mr feature, but I have commit access there, so..

Richard

Sent by mobile; excuse my brevity.

**Comment by brabalan** [comment]
Great! I realize it is a commit feature, but since I could not find where to report bugs there and it is about vcsh integration, I submitted it here.

**Comment by RichiH** [comment]
Try https://github.com/RichiH/myrepos/commit/c6a37fa0d2309fe6a16948ec33b7ad78899dec53 please.

**Comment by brabalan** [comment]
It’s working great, thanks!
