### ISSUE TITLE
$VCSH_BASE/*.git needs nullglob option

### ISSUE THREAD

**Issue by Dieterbe** [RichiH/vcsh#2]
this glob expands incorrectly when there are no matches.
so you probably need to enable nullglob for it.

```
elif [ "$1" = 'list' ]; then
         for i in $VCSH_BASE/*.git; do
```

With pure zsh, i believe you can

```
for i in $VCSH_BASE/*.git(N)
```

with posix sh, not sure.

**Comment by alerque** [comment]
Reviewing the current state of the code I'm pretty sure this has been fixed another way and is obsolete. If not please do chime in with a comment and we'll take another look.
