### ISSUE TITLE
shell completion not completing anything after the git subcommand

### ISSUE THREAD

**Issue by alexconst** [RichiH/vcsh#200]
When I try to run a command such as `vcsh mydotfiles add <TAB>` zsh gets stuck and doesn't cycle through any file, even when I type an initial character.
Note: typing  `vcsh mydotfiles <TAB>` completes git commands. It is after the git command that things break.

I initially thought this was a problem with prezto (ref: https://github.com/sorin-ionescu/prezto/issues/1119 ) but then I tested this with latest `_vcsh` from github (overwriting the one from Jessie) and also with a blank state zsh environment with `.zshrc` as follows:

```
zstyle :compinstall filename '$HOME/.zshrc'
zstyle ':completion:*' special-dirs true

autoload -Uz compinit
compinit
```

Any thoughts on this?

**Comment by danielshahaf** [comment]
Fixed by #225.
