### ISSUE TITLE
vcsh with git annex?

### ISSUE THREAD

**Issue by tjaartvdwalt** [RichiH/vcsh#201]
Hi, thanks for a great project!

I am thinking about a backup strategy for `$HOME` on my new laptop. I have previously used `vcsh`, but my Git repos can easily grow beyond what online git services will allow.

More recently I have encountered [Git Annex](http://git-annex.branchable.com/). I assume using Git Annex with vcsh *should work* since Git Annex does not change the Git interface, only the backend.

Is anyone using this configuration?

**Edit**
After some more thought, I realized that Git Annex will create symlinks to all the files in the repository. That would certainly be undesirable in `$HOME`. At least for me.

**Comment by alerque** [comment]
Git annex can be run in other modes other than symlinking. But that doesn't seem very relevant here. using vcsh helps split up your home directory into multiple repositories while keeping them out of each other's hair. This functionality will work the same whether for a plain git repo or one with annex or lfs. Git LFS is another option that doesn't use symlinks and takes a different approach to storing big blobs, but is also more suited for a central file repository than a distributed system. I prefer annex for a number of reasons and it works fine with vcsh. Any way you shake it though you shouldn't be putting ALL your home stuff in it. If your home directory stuff is too large for online git services you are probably doing something wrong. For example dotfiles shouldn't be in the same repo as your documents, and projects that are themselves version controlled shouldn't be under some parent vcs, nor should things like ~/Music and ~/Pictures and ~/Documents all end up in the same repo. Using vcsh (and mr) can help manage a plethora of repos inside home for various purposes allowing you to use the right storage technology for each.
