### ISSUE TITLE
Run shellcheck and checkbashisms

### ISSUE THREAD

**Issue by ao2** [RichiH/vcsh#249]
Hi,

I noticed some messages when running `shellcheck` or `checkbashisms` on `vcsh`, there are some false-positives but there are also some useful suggestions.

Would you accept patches to address those?

Ciao,
   Antonio

**Comment by alerque** [comment]
VCSH should be fully POSIX compatible. If there are bashisms leaking in then yes we could accept patches to fix them.

Shellcheck is a mixed bag, and I think I'd like to hold off on running it just for a bit, at least until we work through the current PR backlog a bit more. Appeasing its sensibilities is going to require touching a lot of lines of code and I'd be more comfortable doing that when it won't cause so many merge conflicts and general confusion. Long term I'll certainly consider it, although lets maybe split this into two issues. This one for anything non-POSIX that has leaked in and a new one for shellcheck/shellharden gripes.
