### ISSUE TITLE
Is mr removed?

### ISSUE THREAD

**Issue by sabrehagen** [RichiH/vcsh#256]
I cloned the codebase and searched for all references to `mr` but couldn't find any functional code that referenced it. Has `mr` been removed, and if so, can the documentation be updated to reflect this change to avoid confusion for newcomers?

**Comment by alerque** [comment]
@sabrehagen Did the above answer your question? I'm going to assume it did, but if there is anything remaining unclear please feel free to comment again and ask, I'll try to clarify how they can/do work together.

**Comment by RichiH** [comment]
Historical context: `vcsh` and `mr` were developed at roughly the same time, and I dimly remember calling `vcsh foreach` `vcsh mr` for some time when I decided not to reply on mr always being there. If @sabrehagen found a super-old version, that might be the confusion. Or one of the many "gitify your life" talks from way back in time.
