### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [RichiH/vcsh#257]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by RichiH** [comment]
"Actively" is not the best word at the moment. It's on my list for 2019 to work through and unblock everything re vcsh. I should have time in a few months to churn through this.

Sorry for the endless delays :(

**Comment by DanielRuf** [comment]
No problem. Thanks for the clarification.

**Comment by RichiH** [comment]
To put this here: I had severe burnout for most of 2019. Between COVID, a new job, and recovering vcsh has not yet made the list, but it's my honest intention to take up proper maintenance again.

**Comment by DanielRuf** [comment]
> To put this here: I had severe burnout for most of 2019. Between COVID, a new job, and recovering vcsh has not yet made the list, but it's my honest intention to take up proper maintenance again.

I completely understand you and the situation in 2019. No pressure from my side. Take the time that you need. I wish all the best and many thanks for your work on this project.

**Comment by alerque** [comment]
I understand too. Been there, done that.

If you want help I'd be willing to pitch in some issue & PR triage or whatever. It's been many years now and I still rely on `vcsh` every day.

**Comment by alerque** [comment]
@RichiH My offer to help maintain this is still open if you're up for it. I have quite a bit of experience lending a hand on OSS projects created or lead by others, if you want references I can show some.
