### ISSUE TITLE
vcsh help nonzero exit code?

### ISSUE THREAD

**Issue by lebedov** [RichiH/vcsh#258]
I noticed that running `vcsh help` in bash results in an exit code of 1. Is that intentional? Oddly, if I specify the illegal option `-h`, the help is displayed with an exit code of 0.

I'm using vcsh 1.20151229.

**Comment by alerque** [comment]
Thanks for reporting this, it was just a logic bug. The case of `vcsh <repo name>` without a command (which defaults to "enter" was catching this before the fall through that was assumed to catch "help".

**Comment by RichiH** [comment]
Thanks to both of you!
