### ISSUE TITLE
Tests fail on master?

### ISSUE THREAD

**Issue by mxmilkiib** [RichiH/vcsh#261]
I've just taken ownership of the vcsh-git pkg in the AUR. It has been pointing to the debian branch, so I'm trying to update it to master.

I got the test dependencies installed, but am I missing something further as I'm getting these errors+fail on attempting to make install;

```
...
==> Starting package()...
t/000-tear-env.t ... skipped: No need to tear down previous env.
t/001-setup-env.t .. ok   
t/100-init.t ....... 1/? 
#   Failed test 'No repos set up yet.'
#   at t/100-init.t line 17.
t/100-init.t ....... 2/? 
#   Failed test at t/100-init.t line 21.

#   Failed test 'Our new repo is there'
#   at t/100-init.t line 25.
No such file or directory at t/100-init.t line 27.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 3.
t/100-init.t ....... Dubious, test returned 2 (wstat 512, 0x200)
Failed 3/3 subtests 
t/300-add.t ........ 1/? 
#   Failed test 'Adding a file works'
#   at t/300-add.t line 27.
t/300-add.t ........ 2/? 
#   Failed test 'Terse output works'
#   at t/300-add.t line 34.
# Looks like you failed 2 tests of 2.
t/300-add.t ........ Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests 
t/950-delete.t ..... 1/? 
#   Failed test 'No repos set up anymore.'
#   at t/950-delete.t line 17.
# Looks like you failed 1 test of 1.
t/950-delete.t ..... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
t/999-tear-env.t ... ok   

Test Summary Report
-------------------
t/100-init.t     (Wstat: 512 Tests: 3 Failed: 3)
  Failed tests:  1-3
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/300-add.t      (Wstat: 512 Tests: 2 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
t/950-delete.t   (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=6, Tests=10,  3 wallclock secs ( 0.07 usr  0.02 sys +  1.85 cusr  1.08 csys =  3.02 CPU)
Result: FAIL
make: *** [Makefile:48: test] Error 1
==> ERROR: A failure occurred in package().
...
```

(I have a hunch the PKGBUILD was pointing to the debian branch *because* of the above because the test dependency package names were in the PKGBUILD but not actually a part of the depends statement.)

Is there an easy fix, or is master just broken atm and I shouldn't bother yet?

**Comment by alerque** [comment]
I have just adopted the vcsh-git package in AUR and migrated it to build from master instead of debian branch. I did not have any trouble with tests and am unable to replicate this issue. Perhaps it was fixed in master since this report.

**Comment by alerque** [comment]
I've been the maintainer of the Arch `vcsh` and `vcsh-git` packages for some time now and indeed just updated them based on todays tagged release (circa 2019). I also setup a CI runner in Ubuntu (see #278) that doesn't show any problems with the test suite. If you know of anything current please feel free to comment and we'll review.
