### ISSUE TITLE
How do I set .gitattributes for an already cloned repo?

### ISSUE THREAD

**Issue by NightMachinary** [RichiH/vcsh#264]
I tried creating the file at `~/.gitattributes.d/REPO_NAME`. I also did `export VCSH_GITATTRIBUTES=y` in my `.zshenv`. But it seems this doesn't work? Do I need to change sth in `~/.config/vcsh/repo.d/REPO_NAME.git/`?

**Comment by tribut** [comment]
This is probably no longer of interest to you, but just in case someone else is looking for this:

You need to change `~/.config/vcsh/repo.d/REPONAME.git/config` and make sure the key `config.attributesfile` is set appropriately (similar to `core.excludesfile`), for example:

~~~~
[core]
...
    excludesfile = .gitignore.d/REPONAME
    attributesfile = .gitattributes.d/REPONAME
~~~~

**Comment by NightMachinary** [comment]
[**@tribut**](https://github.com/tribut) commented on [Jul 7, 2020, 5:49 PM GMT+4:30](https://github.com/RichiH/vcsh/issues/264#issuecomment-654852813 "2020-07-07T13:19:45Z - Replied by Github Reply Comments"):
> This is probably no longer of interest to you, but just in case someone else is looking for this:
> 
> You need to change `~/.config/vcsh/repo.d/REPONAME.git/config` and make sure the key `config.attributesfile` is set appropriately (similar to `core.excludesfile`), for example:
> 
> ```
> [core]
> ...
>     excludesfile = .gitignore.d/REPONAME
>     attributesfile = .gitattributes.d/REPONAME
> ```

Where is this `.gitignore.d/REPONAME` relative to? Is it `REPO_ROOT/.gitignore.d/REPONAME`? Or `~/.gitignore.d/REPONAME`?

**Comment by tribut** [comment]
It's relative to your git repository's toplevel folder, so `~/.gitignore.d/REPONAME` (or more precisely `$(vcsh run REPONAME git rev-parse --show-toplevel)/.gitignore.d/REPONAME`).

**Comment by NightMachinary** [comment]
@tribut Adding this info to the docs would be help others, too. Thanks!
