### ISSUE TITLE
Global .gitignores is not honored

### ISSUE THREAD

**Issue by NightMachinary** [RichiH/vcsh#265]
I have set a global ignore file. It is honored by normal repos:

```
$ git check-ignore --verbose --no-index --non-matching '.#sth'
/Users/evar/.gitignore_global:14:.\#*	.#sth
```

But not by `vcsh`:

```
$ vcsh .shells check-ignore --verbose --no-index --non-matching ~'/scripts/zsh/.#load-first.zsh'
::	/Users/evar/scripts/zsh/.#load-first.zsh
```

**Comment by madduck** [comment]
Where are you configuring that file, @NightMachinary? In `~/.gitconfig`:`core.ignoresFile`? Because that is overridden by `vcsh` for each repository (see `write-gitignore`), and there seems to be no way to have a global version in addition to a per-repo.

**Comment by alerque** [comment]
I think this falls in roughly the same box as #267. Normal Git repositories and VCSH managed repositories are in different castles. Per [my comment there](https://github.com/RichiH/vcsh/issues/267#issuecomment-812473816) it's also quite possible for that to be a good thing: normal Git usage may **want to** ignore files that are tracked by VCSH.

If I'm missing something here or the current options for `$VCSH_GITIGNORE` are lacking somehow please feel free to comment again and I'll re-evaluate. For now the way I see it I can't justify why trying to use the same ignore chain would be a good thing.
