### ISSUE TITLE
Add the `dotfile-manager` tag

### ISSUE THREAD

**Issue by jwatt** [RichiH/vcsh#266]
Other popular dotfiles managers have the [dotfile-manager](https://github.com/topics/dotfile-manager) and other handy tags on their project. For example:

https://github.com/TheLocehiliosan/yadm
https://github.com/andsens/homeshick

It would be helpful if this project could add some of those too to make be more discoverable.

**Comment by alerque** [comment]
I don't have enough magic beens to add this topic tag to the GitHub project, but I agree this would be a good small gesture. The star based sorting would put us up there in the top 4 and I see this topic linked from several posts around the web.

**Comment by RichiH** [comment]
Interesting... I added what seemed to make sense. If anything's missing, just let me know.

**Comment by RichiH** [comment]
Thanks @jwatt !
