### ISSUE TITLE
Offer to help maintain this project

### ISSUE THREAD

**Issue by alerque** [RichiH/vcsh#275]
This in a continuation of #257. The OP's question about the status quo may have been answered, but I believe the current status could be improved by adding another maintainer to the project. [My offer to help](https://github.com/RichiH/vcsh/issues/257#issuecomment-776747130) still stands and I ask @RichH to give this a second look and the community of users that care about this project to look around at my track record and comment if there are any concerns or endorsements.

I don't think it's any disparagement about Richard to note that in the world of FOSS software having one benevolent dictator managing a project leaves those projects subject to time and motivation constraints that don't always work out the way we hope they will. I have no doubt he has the best intentions to jump back into maintaining this, but also it's been several years where things have languished, issues and PRs have piled up without review, and nothing has progressed.

There isn't a *lot* to do as `vcsh` is a pretty stable product as it is, but there are rough edges that could be improved and a lot of community contributions that could be reviewed (not always to say yes, but at zero feedback on contributions is one way projects die). One major pain point for any project is a lack of issue triage.

Issue triage, community management, and polishing up rough edges are all things I‌ can contribute towards. Furthermore I have a long track record of getting involved in FOSS projects that I didn't start but do now actively maintain and I'd like to think I've earned some trust in every past case. I've help revitalize everything from VIM plugins like [nerdcommenter](https://github.com/preservim/nerdcommenter), [tagbar](https://github.com/preservim/tagbar), and others to becoming the primary active developer on [The SILE‌ Typesetter](https://sile-typesetter.org/) to helping streamline the release process for [harfbuzz](https://github.com/harfbuzz/harfbuzz/releases). I've been elected as a community moderator at several StackExchange sites, have extensive *nix experience through continual use over 25 years, have packaged thousands of projects for release in multiple distros (PLD Linux, Arch Linux, Ubuntu, Debian, Homebrew, Nix, and others). All of these things are relevant to being trustworthy to help oversee a project like this one.

Perhaps more crucially, I depend on `vcsh` every day and love what it does. I don't want to come in with a heavy hand to move all the cheese, I just want to see the bugs and edge cases cleaned up and the community happy with it as a project so it continues to survive and be relevant for years to come.

Please give it some consideration Richard. Even if you were 100% sure of having a huge chunk of time and motivation coming up next week, would it be a bad thing to have help with issue triage? Would an extra set of hands testing and reviewing contributions be a bad thing? Are you worried I'd take over and take it in a direction you didn't like? Are you concerned with security?

**Comment by RichiH** [comment]
Thank you. I will reach out for a quick call, and make you a co-maintainer after.

The dynamic from my end is a downward spiral of feeling responsible, ENOTIME, feeling worse, ignoring the problem, burnout at work with several markers of depression, and sliding into a pandemic right when I started to recover from said burnout.

Not good, not fair to the users, and not an excuse, merely an explanation.

No idea why, but this issue unblocked me mentally to quite some extent. Thank you.

**Comment by alerque** [comment]
Hey, no worries, I get it. I've been through a lot of the same issues and am actually not in such a different boat even now. There are several absolute catastrophes looming in my life for similar reasons. At least as far as FOSS projects go, the ones I most enjoy contributing too are the ones where I'm not solely responsible for! Having other maintainers on board that you can trade off with or even just let stuff slide for a while and then jump in when you have the bandwidth is quite freeing. It doesn't solve the work or personal issues, but FOSS responsibilities shouldn't be an added stress point that get ignored and put off because you know the buck stops with you and even starting becomes an unwelcome task.

I guess we'll chat in a few hours.

**Comment by RichiH** [comment]
Done :)
