### ISSUE TITLE
Refactor to please shellcheck / shellharden

### ISSUE THREAD

**Issue by alerque** [RichiH/vcsh#279]
Split out of #249...

I have mixed feelings about `shellcheck`/`shellharden`. I don't always like the style choice mandated even in cases where a live person can verify that no problem is present, but I do like the normalization and consistency. They can actually save a lot of grief chasing elusive bugs and security issues.

In any event, **if** we do go down that road, [as I mentioned](https://github.com/RichiH/vcsh/issues/249#issuecomment-810066745) I'd prefer to do it sometime after the PR churn has settled down a bit. We have quite a few things to consider before doing something that would make merges that much more work.

**Comment by lyda** [comment]
Excellent. I'm also not keen on some of `shellcheck`'s suggestions but it has caught a slew of bugs for me over the years so I've mainly chosen to humour it. In my experience, if you can get it clean, bugs in future changes will get caught far quicker.
