### ISSUE TITLE
`master` is hardcoded as default remote branch

### ISSUE THREAD

**Issue by RichiH** [RichiH/vcsh#294]
This is surprisingly intricate.

https://github.com/RichiH/vcsh/blob/776d3f910aefe26e621b26ccb46474621e5b32bc/vcsh#L620 is an easy change assuming `main` as the local.

https://github.com/RichiH/vcsh/blob/776d3f910aefe26e621b26ccb46474621e5b32bc/vcsh#L176 might need a check for `main`, then `trunk`, then `master`, because of Git's inability to signal what the canonical remote branch is.

**Comment by RichiH** [comment]
In the spirit of making things even more complicated, Git also suggests `development` because of course it did.

````
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
````

**Comment by alerque** [comment]
I think there is a way to get the default remote branch name, but maybe only while you are cloning...

**Comment by RichiH** [comment]
`git symbolic-ref refs/remotes/origin/HEAD` seems to work, but only after a remote has been set.
