### ISSUE TITLE
Cut beta release v2.0.0-beta and let simmer

### ISSUE THREAD

**Issue by alerque** [RichiH/vcsh#306]
As part of the release cycle for v2, we've agreed to tag at least one prerelease. According to [SemVer](https://semver.org) this should be in the format should be similar to `v2.0.0-rc.1`, `v2.0.0-beta`, or `v2.0.0-beta.1`.

- [x] Fix current known issues with known fixes that we're just hashing out the details. I think this means closing all open PRs in the [v2 milestone](https://github.com/RichiH/vcsh/milestone/1).
- [x] Tag `v2.0.0-beta` (or `-beta.1`) (no update to changelog for this)
- [x] Announce on IRC in \#vcs-home
- [x] Announce anywhere else we can reasonably expect interested testers
- [x] Wait at least N-days for any trouble to surface.

**Comment by RichiH** [comment]
I think we should cut earlier rather than later; maybe a `-beta` once https://github.com/RichiH/vcsh/pull/302 is merged?

**Comment by alerque** [comment]
I'm good with `-beta`. It was the RC label that has me hung up because it isn't technically that with our current release procedure.

**Comment by alerque** [comment]
Our CI workflow refused to run the release for the beta tag because the changelog didn't match. I'll add some handling to produce pre-releases as opposed to releases for such tag patterns.

**Comment by RichiH** [comment]
Thanks! Will those build standalone as well?

**Comment by alerque** [comment]
Yes.

**Comment by alerque** [comment]
Okay so I had, er, [a "couple" misadentures](https://github.com/alerque/vcsh/actions/workflows/release.yml) on my fork setting up CI to mark `-(alpha|beta|rc).\d+` tags as pre-releases but otherwise compile them the same way it would for releases. I think it finally behaves the way I imagined it should, so a beta tag is incomming to this repo. Sorry it took so long but I had to fit all those test runs in between real life.

**Comment by RichiH** [comment]
No worries at all. Thanks for the work!

**Comment by alerque** [comment]
So far the beta process is not knocking my socks off. Only one person has even downloaded the tar ball, and that was me testing out pending changes for the Arch Linux package. Not a single person besides me has touched it. The standalone script has been download 4 times, of which I was 3 of them. That's one other person that has *maybe* looked at this. :disappointed: Arch does have a VCS package that I know has some usage but we have no way of quantifying, and the number of `git clones` did spike the day we posted the beta, but still.

It's possible some have tried to download the `git archive` generated "Source code" links, but they wouldn't have been able to run those. :shrug: 

I'm surprised actually it has taken so long for people to even notice that they can't just blinding download the raw script from HEAD any more. Maybe 3 people have even noticed? ...in the 4 weeks since HEAD stopped having the script. I guess maybe that's good: not *everybody* is `curl | bash`ing it! I guess I can keep hoping that the majority of use is from distro packages.

**Comment by RichiH** [comment]
In my experience, most people consider `vcsh` "touch once, it will work forever" so it would stand to reason that they don't track closely. Number of stars also went up, so there's definitely interest. On the plus side, people can't really complain once 2.0 is out :p

**Comment by alerque** [comment]
I see we got a few more downloads and still zero reports. Well except mine. I'm not in a hurry but I'll probably poke at making sure tidbits are cleaned up over the next day or two. I'm not in a good place this week or weekend to attend to post-release anything, maybe Monday?

In any case I think we can call the beta stage a success. I'm not planning on another beta before release. Of course issues could get opened at any time and we can re-evaluate but it seems to me this tracking issue has done its duty.
