### ISSUE TITLE
Licensing for derivative/inspired works?

### ISSUE THREAD

**Issue by ErichDonGubler** [RichiH/vcsh#317]
**Conclusion:** Capisco (the project that motivated my question) will use GPL 3.0, because I'd like to remain mostly compatible with the `vcsh` community, and appreciate @RichiH's perspective [below](https://github.com/RichiH/vcsh/issues/317#issuecomment-942082614).

Original OP:

---

Hey all! This isn't directly related to the production of this project, but I figured it would be an interesting enough topic that having it searchable in GH issues would be good. Also, I don't use IRC or mailing lists in general, so this is a lot more comfortable place for me to open some initial dialogue for something I hope will be a short conversation. :)

I'm building a dotfiles manager alternative at https://github.com/erichdongubler/capisco that draws some heavy inspiration from `vcsh` for its `overlay` repos. I don't mind licensing until GPL-2.0, since that's a pretty consumer-friendly licensing option, but it'd be nice if I could license that project under something maybe more permissive, for the sake of encouraging people to contribute. Are folks here open to me making something that could technically be considered a derivative work under a different license?

**Comment by ErichDonGubler** [comment]
Downstream issue link for convenience: https://github.com/erichdongubler/capisco/issues/9

**Comment by alerque** [comment]
Most software licensing models apply to "copied code from" not "got inspired by". Are you wishing to copy any actual lines of code?

**Comment by alerque** [comment]
At this point there have been a *lot* of contributors and re licensing to a more permission license would require sign-off from **all** of them (or rewriting the contributions of anyone that didn't approve). That's a prohibitively difficult process for no concrete gain and I doubt very highly whether it would happen even if we wanted it to. I'm not a huge fan of more permissive licenses myself and am more comfortable contributing to GPL projects than MIT or others you may have in mind. Personally I'm not a hard-core copy-left-ony guy, but I wouldn't be surprised if there were several in the contributor list.

That leaves you deciding whether you want to stay under GPL or not copy code. You can be inspired by the concepts and use `git` under its own terms, but you can't copy code without following the terms.

**Comment by alerque** [comment]
Also just so you are aware, both myself and the original author are at least somewhat open to the idea of rewriting `vcsh` in Rust. It's not clear to me what the scope of your project is, but it's possible that if it's close enough we could abstract the main parts of this as a Rust library, then write two CLI clients, one that accepts arguments the way `vcsh` does and focuses on home directory management (basically a drop in replacement) and one CLI that does whatever else you saw it doing.

**Comment by RichiH** [comment]
I personally prefer reciprocal licenses over non-reciprocal ones myself.

As e.g. the Linux kernel shows, GPL 2.0 is not a blocker for wide adoption.

**Comment by ErichDonGubler** [comment]
> It's not clear to me what the scope of your project is, but it's possible that if it's close enough we could abstract the main parts of this as a Rust library, then write two CLI clients, one that accepts arguments the way `vcsh` does and focuses on home directory management (basically a drop in replacement) and one CLI that does whatever else you saw it doing.

Hehe, I haven't "unveiled" (read: taken the time to write intro docs) to Capisco yet, but it's basically intended to be a near-superset of `vcsh`, and try to make a cohesive interface abstracting over managing `vcsh`-like repos (called "overlay" repos there) and normal Git repos ("standalone" repos). I think that there's definitely room for just having a `vcsh` port, though!

On that note, licensing is not my primary concern with this tooling, but sharing, and I'd love to share something that lets y'all experiment with porting to Rust! :) I think we could share:

1. My fork of `xdg` (I just need to polish up [Windows support](https://github.com/erichdongubler/rust-xdg/tree/windows-support) into a PR, it's 95% ready to go).
2. `DynGit`, an interface/set of implementations for invoking Git. Currently, it only implements commands via the `git` binary found via `PATH`, but that should be feature parity with `vcsh` currently, I think?
3. The private [`RepoDb::new_overlay` method](https://github.com/ErichDonGubler/capisco/blob/ed9ca657bfec8026baf6843d6e9cde265f700b06/src/bin/cpsc/runner/repo_db.rs#L326-L385) would likely be a good thing to copy for yourselves; the logic is fairly simple instrumentation of (2), and otherwise has a bunch of application-specific stuff that an implementation of `vcsh` likely wouldn't want/need.

**Comment by ErichDonGubler** [comment]
> Most software licensing models apply to "copied code from" not "got inspired by". Are you wishing to copy any actual lines of code?

To be clear, "inspiration", in this case, means that while I have not done any porting line-by-line, I _did_ consult with recent `vcsh` source code to validate that I'm getting feature parity, particularly with the [`RepoDb::new_overlay`](https://github.com/ErichDonGubler/capisco/blob/ed9ca657bfec8026baf6843d6e9cde265f700b06/src/bin/cpsc/runner/repo_db.rs#L326-L385) method I mentioned above.

This is actually a gray area WRT license enforcement AFAIK -- in my understanding as a downstream producer, the argument to consider here is whether Capisco is a derivative work of `vcsh`. The best source I've found describing the situation is...dry, but thorough: https://copyleft.org/guide/comprehensive-gpl-guidech5.html. That aside, I consider you as the license holders as free to determine whether or not you'll hold me to GPL license terms. I figured it was better to ask and build some ties than just make something in the same space when `vcsh`. :)

My inclination is to license under GPL, if that's your preference. I have no strong reasons to prefer a more open license, except familiarity.

**Comment by ErichDonGubler** [comment]
Wanted to ask before I finally commited to GPL for Capisco: do y'all have strong opinions on GPL 2.0 vs GPL 3.0?

**Comment by ErichDonGubler** [comment]
I think I'll move forward with GPL 3.0 for Capisco, then. :) I feel pretty good about it at this point.

WRT migration or deprecation, there's some open space with getting functional equivalents to `vcsh enter` (questions like, "What shell should we use?") and the lifecycle hooks (users will likely have to deal with the ramifications of answers to the previous questions about shells), but I hope that I can get some interesting parity in Capisco design-wise. We might want to discuss cross-platform design together at some point!
