### ISSUE TITLE
[BUG] interactive commands can't press ENTER

### ISSUE THREAD

**Issue by NightMachinary** [RichiH/vcsh#324]
During interactive commands, pressing ENTER produces `^M` instead of doing what it usually does. This doesn't happen when I use git normally.

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/36224762/155218985-7647c2ce-799d-4cf5-acb7-eda38117bdc3.png">

**Comment by NightMachinary** [comment]
I now doubt if this is actually a `vcsh` bug.

- https://askubuntu.com/questions/441744/pressing-enter-produces-m-instead-of-a-newline

Closing the issue for now.

**Comment by alerque** [comment]
Just for the record, I am able to use `vcsh <repo_name> add --patch` just fine. This is something to do with the shell you are spawning. I'm using ZSH, which might be different than Bash.
