### ISSUE TITLE
Link to longer docs from README

### ISSUE THREAD

**Issue by openjck** [RichiH/vcsh#328]
Thanks for this great tool.

I think it would be helpful if the root README linked to the [longer documentation](https://github.com/RichiH/vcsh/tree/main/doc). It took me a bit to find it initially, and just now, I had a bit of difficulty remembering where it was.

I'm happy to open a pull request, but I figured you might have an opinion on where the link should go. You can let me know if you'd like to open a pull request, though. Whatever's easiest for you.

**Comment by RichiH** [comment]
Good idea; feel free to send a PR.

Thanks!@
