### ISSUE TITLE
Staged files are deleted upon `vcsh enter`

### ISSUE THREAD

**Issue by dukwon** [RichiH/vcsh#331]
Steps to reproduce:

```
$ touch test_file
$ vcsh $repo add test_file
$ vcsh enter $repo
$ ls test_file
ls: cannot access 'test_file': No such file or directory
```

**Comment by alerque** [comment]
I cannot reproduce it, and looking at the code for what `vcsh enter` does I'm skeptical that this is a bug in VCSH. I'm willing to keep reviewing if you can give us more information about your setup.

What version of `vcsh` are you using? Do you have any hooks defined for VCSH's `pre-hook`? Have you reviewed your Git config to make sure that isn't triggering some weirdness?

**Comment by dukwon** [comment]
My mistake, it is indeed a consequence of the hooks I have installed from https://git.ao2.it/config/vcsh.git/

Closing the issue as this is not the right repo. Sorry for the noise
