### ISSUE TITLE
.gitignore.d is broken for files in subdirs due to git behavior revert

### ISSUE THREAD

**Issue by jwhitley** [RichiH/vcsh#333]
**Repro steps**
1. Enter a vcsh-controlled repository, e.g. via `vcsh foo`
2. Ensure that `.gitignore.d/foo` exists and is up-to-date. Update via `vcsh write-gitignore foo` if needed.
3. `git add <some modified file, in a subdirectory and already tracked by foo and in the above gitignore>`

**Expected results**
`git add` just works.

**Actual results**
`git add` produces the "force me" error message, such as the following for a file under `~/.config`:
```
The following paths are ignored by one of your .gitignore files:
.config
```

Ugh, it looks like git [reverted the enhancement regarding gitignore parent directories](https://github.com/git/git/commit/5cee349370bd2dce48d0d653ab4ce99bb79a3415), and we need to resurrect the old code that added each parent directory of a controlled file into `.gitignore.d/foo`:

```
*
!/.config
!/.config/bar
!/.config/bar/baz
!/.config/bar/baz/something.txt
```

**Notes**
The 2.43.0 gitignore man page includes this note, which I used to trace back to the revert commit above:
> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. 

**Versions**
vcsh: 2.0.5 standalone
git: 2.43.0

**Comment by jwhitley** [comment]
Ah, there it is. #196 needs to be reverted, since the corresponding change was reverted (I think all the way back around git 2.8, if I'm reading right 😳)

**Comment by alerque** [comment]
Yuck. Thanks for tracking this down (and I was affected too bug figured it was something weird I did locally and hadn't tracked it down with a test case).

Would you like to submit a PR with the revert?

**Comment by jwhitley** [comment]
Literally working on the PR right now. ;-)
