### ISSUE TITLE
PRs failing lint checks b/c editorconfig-checker upgrade required

### ISSUE THREAD

**Issue by jwhitley** [RichiH/vcsh#335]
[Lifting this to its own issue so it doesn't get lost. –J]

As noted in my comments on #334, editorconfig-checker is failing its lint check on the PR CI runs because it's scanning inside the `.git` directory and throwing a bunch of bogus errors as a result. An update to the editorconfig checker Docker image is required, to >=2.7.1. Might as well bump to latest release of 2.7.2. See editorconfig-checker/editorconfig-checker#268 for details.

**Comment by alerque** [comment]
Fixed in 937022f51e7ec98d70b5e822d8e06b0ed1ab0bcf.

Hopefully the bump to release artifact tooling doesn't mess up our next release. I looked everything over for relevant changes but without *trying* it isn't always clear what might have broken when bumping these Actions.
