### ISSUE TITLE
man page incomplete

### ISSUE THREAD

**Issue by lyderic** [RichiH/vcsh#338]
`man vcsh` displays an incomplete man page. The last line of this man page is, verbatim:

````
just append any kind of string to order them. A system of pre-run,
````

A text finishing with a comma is clearly not right.

I have installed vcsh on two machines, and I get the same result:

1. On Arch, I installed it with: `pacman -S vcsh`
2. On Ubuntu 22.04, I downloaded the tarball and ran `./configure ; make ; sudo make install`

In both cases, the version I ran is `2.0.7`

**Comment by alerque** [comment]
Thanks for the report. I can confirm something is going sideways with man page regeneration. I'm looking into it.

**Comment by alerque** [comment]
It looks like newer/current versions of `ronn` must me handling tag syntax differently. Possible this was always wrong and just getting ignored before:

```
warn: unrecognized inline tag: ["pre-run.10"]
warn: unrecognized block tag: ["pre-run.20"]
```

Why it only throws a warning but actually dies behind the scenes with partial output is beyond me and I have no interest in Ruby to figure it out.
