### ISSUE TITLE
Feature request: Different approach to submodules

### ISSUE THREAD

**Issue by ironhouzi** [RichiH/vcsh#85]
Please excuse my suggestion if I'm being ignorant here, but I though maybe I had an idea to provide a clean cut way to deal with submodules:

Implement a script that just creates a specific file whenever it comes across a git repo within the directory vcsh is set to monitor. E.g. ~/.vim/bundle/.subrepos.vcsh This file contains the git address to all the remote repositories within the parent directory containing any number of git repos. I don't know much about git, but I was thinking that vcsh would at least be able to parse this file and clone all the repos, whenever vcsh would create the set of dotfiles on a new system.

**Comment by alerque** [comment]
Thanks for reporting this. I think I understand the gist of the request, but unfortunately this approach is not practical for a number of reasons. Submodules are a bit of a sore subject really, they have been a constant pain point in Git.

See issue #27 for further discussion on the issue of submodules and why they are problematic for `vcsh`. Anything we do to "fix" or work around them would require review of that mega thread, so I'm going to close this issue as something between a "duplicate" and "won't fix".

If you have further questions about how to setup VCSH in a way that plays nicely with other Git repositories in your `$HOME` directory please let me know. It's likely the answer we recommend is going to involve [myrepos](https://myrepos.branchable.com/) to manage the clone process for other repositories and VCSH to manage the config file for myrepos.
