### ISSUE TITLE
support for recursive clone?

### ISSUE THREAD

**Issue by gliptak** [RichiH/vcsh#94]
I'm trying to run

```
 $ vcsh version
 vcsh 1.20130724
 $ vcsh clone --recurse-submodules https://github.com/spf13/spf13-vim.git
```

and receive the following error

```
fatal: Could not switch to 'https://github.com/spf13/': No such file or directory
vcsh: fatal: no repository found for 'spf13-vim'
```

Am I using the right syntax here?

Thanks

**Comment by gliptak** [comment]
With current version:
```
$ vcsh version
vcsh 1.20151229
git version 2.7.4
$ vcsh clone --recurse-submodules https://github.com/spf13/spf13-vim.git
fatal: Could not switch to 'https://github.com/spf13/': No such file or directory
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
fatal: not in a git directory
vcsh: fatal: no repository found for 'spf13-vim'
```

**Comment by klaernie** [comment]
@gliptak I think leaving the vcsh repo name out and giving options to the `git clone` underneath is mutually exclusive. vcsh sees two arguments passed in, so it treats `--recurse-submodules` as the URL and `https://github.com/spf13/spf13-vim.git` as the repository name.

@RichiH I think `init()` during init it takes the URL as the `$GIT_DIR`:
```
…
+ init
+ hook pre-init
+ [ -x /home/kandre/.config/vcsh/hooks-enabled/pre-init* ]
+ continue
+ [ -x /home/kandre/.config/vcsh/hooks-enabled/spf13-vim.pre-init* ]
+ continue
+ [ ! -e https://github.com/spf13/spf13-vim.git ]
+ mkdir -p /home/kandre
+ cd /home/kandre
+ git init --shared=0600
fatal: Could not switch to 'https://github.com/spf13/': No such file or directory
+ upgrade
+ hook pre-upgrade
```

**Comment by gliptak** [comment]
@klaernie Is there a different syntax to be used? Thanks

**Comment by klaernie** [comment]
@gliptak just `vcsh clone https://github.com/spf13/spf13-vim.git`, then `vcsh spf13-vim submodule update --init --recursive`. This will simply break what you attempted into two steps, as `vcsh clone` is not the same as `git clone`. I tried this with a temporary  `$HOME` and it worked flawlessly.

**Comment by gliptak** [comment]
Thanks @klaernie
